services:
- type: web
  name: interactive-csv-analysis-query
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "streamlit run app.py"
  envVars:
  - key: STREAMLIT_ENV
    value: production
  - key: PORT
    value: "8501"
